name: Build for Android

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    #strategy:
    #  matrix:
    #    abi: ['armeabi-v7a', 'arm64-v8a', 'x86_64']
    #    # 24 : Android 7.1, 26: Android 8, 28: Android 9, 29: Android 10
    #    target-api: ['29']
    #    build-tools: ['30.0.2']
    #    qt-version: ['5.15.1']
    #    build-type: ['Release']
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        target: 'android'
        version: '5.12.6'
        arch: 'android_armv7'
        modules: 'qtcharts qtwebengine qtscript'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
    - name: qmake apk
      run: |
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
        cd SSTest/QtProjects
        qmake
        make -j12
        make apk
    - name: show filetrees
      run: |
        cd SSTest/QtProjects
        ls -R
    - uses: actions/upload-artifact@v1
      with:
        name: Debug-APK
        path: cd SSTest/QtProjects/android-build//build/outputs/apk/debug/android-build-debug.apk
